### ISSUE TITLE
Discussion for "A Pretty Little Bit of Rsync"

### ISSUE THREAD

**Issue by nchlswhttkr** [nchlswhttkr/website#22]
This issue thread can be used to leave comments on https://nicholas.cloud/blog/a-pretty-little-bit-of-rsync/!

It's powered by https://utteranc.es/, and you can comment below!

**Comment by etopiei** [comment]
Loved the post Nick, also was thinking of using utterances for my blog, how's the setup with that?

**Comment by nchlswhttkr** [comment]
Pretty hands-free from the [utterances](https://utteranc.es/#how-it-works) guide, mostly just enabling the OAuth integration. 

There's a form you fill out which sets up the client script with your desired configuration, so from there it's just a matter of including it in the template for your blog posts.

Utterances can automatically create issues for new posts, but right now I do it myself and pass the issue ID to the client script.
